New Autonomy Layout
gt-marine-robotics-group/Pontus pull request #43
Opened 2024-07-12 08:28 UTC by chachmu

This adds the new system for organizing our autonomy. A very basic explanation is that individual tasks inherit from the BaseTask class and use state machines to complete their task. Multiple successive tasks are organized into different runs (prequal, finals, etc.) which inherit from the BaseRun class.

The BaseTask class provides some simple preprepared functionality to publish a debug string and an overlay image. I also added a small helper class that handles thresholding CV2 images so we don't have to recreate the wheel in every task that needs thresholding.

In the future it would be good to automate some more of the setup and state machine handling for the BaseTask class. We might also consider switching to StrEnums with auto() instead of the current type.

2024-09-14 04:36 UTC, Jeff300fang commented on pontus_autonomy/pontus_autonomy/base_run.py
nit: 

`task = task()` is a bit confusing. Without tracing `run_task`, one might be confused on what calling `task()` does. I suggest something like:

```
def run_task(self, Task):
      task = Task()
      ...
 ```
 or
```
def run_task(self, TaskClass):
      task = TaskClass()
      ...
 ```

2024-09-14 18:11 UTC, Jeff300fang requested changes
Looks good.

2024-09-14 18:11 UTC, Jeff300fang commented on pontus_autonomy/pontus_autonomy/prequalification_run.py
> +        result = self.run_task(GateTask)
Outside of prequal, how should information, such as the direction to circumnavigate the buoy, which is discovered during `self.run_task(GateTask)`, be passed back to the Run?

2024-09-14 19:54 UTC, chachmu commented on pontus_autonomy/pontus_autonomy/helpers/cv_threshold.py
> +        return self.mask
I guess you could try to generalize it, but you shouldn't ever have more than 2 sets of values anyway. The only reason for multiple masks was to handle what happens when you have a threshold that you want to wrap around the limits of the hsv values (for example if you want to detect red you need to look for hues from 170-10 degrees)

2024-09-14 19:59 UTC, chachmu commented on pontus_autonomy/pontus_autonomy/helpers/cv_threshold.py
> +        self.masked = None
No, `mask` and `masked` are different, I should probably add a comment to the code. `mask` is the black and white mask that tells you which parts of the image you want, `masked` is what you get after multiplying the mask with the image to get black everywhere except the areas that you were trying to select and color in those regions.

2024-09-21 20:06 UTC, Jeff300fang approved these changes

2024-09-22 18:53 UTC, merged